import { Alert, Linking, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Muted, Title, colors } from '@/src/components/ui';
import { decideRoleApplication, getPendingRoleApplications, getPrivateApplicationDocumentUrl } from '@/src/lib/adminApplications';

export default function AdminApplications(){
  const qc=useQueryClient();
  const query=useQuery({queryKey:['admin-role-applications'],queryFn:getPendingRoleApplications,refetchInterval:15000});
  async function decide(kind:'merchant'|'driver',id:string,status:'approved'|'rejected'){try{await decideRoleApplication(kind,id,status);await qc.invalidateQueries({queryKey:['admin-role-applications']});await qc.invalidateQueries({queryKey:['admin-overview']});Alert.alert('تم',status==='approved'?'تمت الموافقة وتفعيل الدور.':'تم رفض الطلب.');}catch(e){Alert.alert('تعذر تنفيذ القرار',e instanceof Error?e.message:'حاول مرة أخرى');}}
  async function openDoc(path?:string|null){if(!path)return;try{await Linking.openURL(await getPrivateApplicationDocumentUrl(path));}catch(e){Alert.alert('تعذر فتح المستند',e instanceof Error?e.message:'حاول مرة أخرى');}}
  return <ScrollView style={s.page} contentContainerStyle={s.content}>
    <View style={s.hero}><Text style={s.kicker}>مراجعة واعتماد</Text><Title>طلبات التجار والمندوبين</Title><Muted>راجع الهوية والموقع والمستندات قبل الموافقة. روابط الرخص مؤقتة وخاصة.</Muted></View>
    <View style={s.counter}><Text style={s.counterText}>تجار قيد المراجعة: {query.data?.merchant.length??0}</Text><Text style={s.counterText}>مندوبون قيد المراجعة: {query.data?.driver.length??0}</Text></View>
    <Title>طلبات التجار</Title>
    {(query.data?.merchant??[]).map((item:any)=><Card key={item.id}>{item.logo_url?<Image source={{uri:item.logo_url}} style={s.logo} contentFit="cover"/>:null}<Text style={s.name}>{item.business_name}</Text><Muted>{item.category} • {item.phone}</Muted><Text style={s.detail}>العنوان: {item.address}</Text><Text style={s.detail}>الموقع: {item.latitude?.toFixed?.(5)??'-'}, {item.longitude?.toFixed?.(5)??'-'}</Text><View style={s.actions}><View style={s.flex}><Button title="موافقة وتفعيل المتجر" onPress={()=>decide('merchant',item.id,'approved')}/></View><View style={s.flex}><Button title="رفض" onPress={()=>decide('merchant',item.id,'rejected')}/></View></View></Card>)}
    {!query.isLoading&&!query.data?.merchant.length?<Muted>لا توجد طلبات تجار معلقة.</Muted>:null}
    <Title>طلبات المندوبين</Title>
    {(query.data?.driver??[]).map((item:any)=><Card key={item.id}><View style={s.driverHead}>{item.profile_photo_url?<Image source={{uri:item.profile_photo_url}} style={s.avatar} contentFit="cover"/>:null}<View style={s.flex}><Text style={s.name}>{item.full_name}</Text><Muted>{item.phone}</Muted><Muted>{item.transport_mode==='bicycle'?'دراجة':`موتوسيكل • ${item.motorcycle_type||item.vehicle_type}`}</Muted></View></View>{item.transport_mode!=='bicycle'?<View style={s.docs}><Doc title="رخصة القيادة — وش" enabled={!!item.driving_license_front_path} onPress={()=>openDoc(item.driving_license_front_path)}/><Doc title="رخصة القيادة — ظهر" enabled={!!item.driving_license_back_path} onPress={()=>openDoc(item.driving_license_back_path)}/><Doc title="رخصة الموتوسيكل — وش" enabled={!!item.vehicle_license_front_path} onPress={()=>openDoc(item.vehicle_license_front_path)}/><Doc title="رخصة الموتوسيكل — ظهر" enabled={!!item.vehicle_license_back_path} onPress={()=>openDoc(item.vehicle_license_back_path)}/></View>:<Muted>المندوب اختار العمل بدراجة؛ لا توجد رخصة موتوسيكل مطلوبة.</Muted>}<View style={s.actions}><View style={s.flex}><Button title="موافقة وتفعيل المندوب" onPress={()=>decide('driver',item.id,'approved')}/></View><View style={s.flex}><Button title="رفض" onPress={()=>decide('driver',item.id,'rejected')}/></View></View></Card>)}
    {!query.isLoading&&!query.data?.driver.length?<Muted>لا توجد طلبات مندوبين معلقة.</Muted>:null}
  </ScrollView>;
}
function Doc({title,enabled,onPress}:{title:string;enabled:boolean;onPress:()=>void}){return <Text accessibilityRole={enabled?'link':undefined} onPress={enabled?onPress:undefined} style={[s.doc,!enabled&&s.docMissing]}>{enabled?'فتح':'ناقص'} • {title}</Text>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fa'},content:{padding:18,paddingBottom:40,gap:14,direction:'rtl'},hero:{backgroundColor:'#182230',borderRadius:28,padding:22,gap:7},kicker:{color:'#fb923c',fontWeight:'900',textAlign:'right'},counter:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'},counterText:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e4e7ec',borderRadius:999,paddingHorizontal:12,paddingVertical:8,fontWeight:'800',color:'#344054'},logo:{width:'100%',height:170,borderRadius:18,backgroundColor:'#eee'},avatar:{width:76,height:76,borderRadius:38,backgroundColor:'#eee'},driverHead:{flexDirection:'row-reverse',alignItems:'center',gap:12},name:{fontSize:19,fontWeight:'900',textAlign:'right',color:colors.text},detail:{textAlign:'right',color:'#344054',lineHeight:22},docs:{gap:7},doc:{backgroundColor:'#f0f9ff',borderRadius:12,padding:11,textAlign:'right',fontWeight:'800',color:'#026aa2',overflow:'hidden'},docMissing:{backgroundColor:'#fef3f2',color:'#b42318'},actions:{flexDirection:'row-reverse',gap:8},flex:{flex:1}});
