import { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Field, Muted, Title, colors } from '@/src/components/ui';
import { createFleetCompany, getAdminFinanceOverview, postWalletAdjustment, setFleetDriver, updateFinanceSettings, updateLoyaltySettings, upsertReward } from '@/src/lib/finance';

const num=(value:string,fallback=0)=>{const n=Number(value);return Number.isFinite(n)?n:fallback;};
const roleLabel:Record<string,string>={customer:'عميل',driver:'مندوب',merchant:'تاجر',all:'الكل'};
const rewardTypeLabel:Record<string,string>={free_delivery:'توصيل مجاني',commission_free_next_order:'طلب بدون عمولة',priority_badge:'ميزة أولوية',custom:'مكافأة مخصصة'};

export default function AdminFinance(){
  const qc=useQueryClient();
  const query=useQuery({queryKey:['admin-finance'],queryFn:getAdminFinanceOverview,refetchInterval:30_000});
  const data=query.data as any;
  const settings=data?.settings;
  const loyalty=data?.loyalty;
  const [busy,setBusy]=useState(false);
  const [direct,setDirect]=useState<string|null>(null);const[fleetDriver,setFleetDriverPct]=useState<string|null>(null);const[fleetPlatform,setFleetPlatform]=useState<string|null>(null);const[merchant,setMerchant]=useState<string|null>(null);
  const [driverDebt,setDriverDebt]=useState<string|null>(null);const[merchantDebt,setMerchantDebt]=useState<string|null>(null);const[fleetDebt,setFleetDebt]=useState<string|null>(null);
  const [enforcement,setEnforcement]=useState<boolean|null>(null);const[ratingBonus,setRatingBonus]=useState<boolean|null>(null);
  const [customerPts,setCustomerPts]=useState<string|null>(null);const[driverPts,setDriverPts]=useState<string|null>(null);const[merchantPts,setMerchantPts]=useState<string|null>(null);const[referralPts,setReferralPts]=useState<string|null>(null);
  const [companyName,setCompanyName]=useState('');const[ownerSearch,setOwnerSearch]=useState('');const[selectedOwner,setSelectedOwner]=useState<string|null>(null);const[companyCut,setCompanyCut]=useState('0');
  const [selectedFleet,setSelectedFleet]=useState<string|null>(null);const[driverSearch,setDriverSearch]=useState('');const[selectedDriver,setSelectedDriver]=useState<string|null>(null);const[driverCut,setDriverCut]=useState('');
  const [walletAmounts,setWalletAmounts]=useState<Record<string,string>>({});
  const [rewardTitle,setRewardTitle]=useState('');const[rewardCost,setRewardCost]=useState('300');const[rewardRole,setRewardRole]=useState<'customer'|'driver'|'merchant'|'all'>('customer');const[rewardType,setRewardType]=useState<'free_delivery'|'commission_free_next_order'|'priority_badge'|'custom'>('free_delivery');

  const rolesByUser=useMemo(()=>{const map=new Map<string,Set<string>>();for(const r of data?.roles??[]){const s=map.get(r.user_id)??new Set<string>();s.add(r.role);map.set(r.user_id,s);}return map;},[data?.roles]);
  const owners=useMemo(()=>{const q=ownerSearch.trim().toLowerCase();return(data?.profiles??[]).filter((p:any)=>!q||`${p.full_name??''} ${p.phone??''}`.toLowerCase().includes(q)).slice(0,8);},[data?.profiles,ownerSearch]);
  const driverCandidates=useMemo(()=>{const q=driverSearch.trim().toLowerCase();return(data?.profiles??[]).filter((p:any)=>rolesByUser.get(p.id)?.has('driver')&&(!q||`${p.full_name??''} ${p.phone??''}`.toLowerCase().includes(q))).slice(0,10);},[data?.profiles,driverSearch,rolesByUser]);
  const debts=useMemo(()=>data?.wallets?.filter((w:any)=>Number(w.balance)<0).sort((a:any,b:any)=>Number(a.balance)-Number(b.balance))??[],[data?.wallets]);
  const totalDebt=debts.reduce((sum:number,w:any)=>sum+Math.abs(Number(w.balance)),0);

  async function refresh(){await qc.invalidateQueries({queryKey:['admin-finance']});}
  async function saveFinance(){if(!settings)return;setBusy(true);try{await updateFinanceSettings({directDriver:num(direct??String(settings.driver_platform_commission_percent)),fleetDriverPlatform:num(fleetDriver??String(settings.fleet_driver_platform_commission_percent)),fleetPlatform:num(fleetPlatform??String(settings.fleet_platform_commission_percent)),merchant:num(merchant??String(settings.merchant_platform_commission_percent)),enforcement:enforcement??Boolean(settings.wallet_enforcement_enabled),driverDebt:num(driverDebt??String(settings.driver_debt_limit)),merchantDebt:num(merchantDebt??String(settings.merchant_debt_limit)),fleetDebt:num(fleetDebt??String(settings.fleet_debt_limit)),ratingBonus:ratingBonus??Boolean(settings.rating_bonus_enabled),ratingRules:[{min:4.8,bonus_percent:10},{min:4.6,bonus_percent:5},{min:4.2,bonus_percent:0},{min:0,bonus_percent:0}]});await refresh();Alert.alert('تم الحفظ','تم تحديث نظام العمولات والمحافظ والتقييم.');}catch(e){Alert.alert('تعذر الحفظ',e instanceof Error?e.message:'حاول مرة أخرى');}finally{setBusy(false);}}
  async function saveLoyalty(){if(!loyalty)return;setBusy(true);try{await updateLoyaltySettings({customerPer10:num(customerPts??String(loyalty.customer_points_per_10)),driverPerDelivery:Math.round(num(driverPts??String(loyalty.driver_points_per_delivery))),merchantPerOrder:Math.round(num(merchantPts??String(loyalty.merchant_points_per_delivered_order))),referral:Math.round(num(referralPts??String(loyalty.referral_points))),enabled:Boolean(loyalty.rewards_enabled)});await refresh();}catch(e){Alert.alert('تعذر تحديث النقاط',e instanceof Error?e.message:'حاول مرة أخرى');}finally{setBusy(false);}}
  async function addCompany(){if(!selectedOwner||companyName.trim().length<2)return;setBusy(true);try{await createFleetCompany({name:companyName,ownerUserId:selectedOwner,driverCommission:num(companyCut)});setCompanyName('');setOwnerSearch('');setSelectedOwner(null);await refresh();Alert.alert('تم إنشاء الشركة','الحساب المختار بقى مدير شركة بصلاحيات مقفولة على شركته ومناديبه فقط.');}catch(e){Alert.alert('تعذر إنشاء الشركة',e instanceof Error?e.message:'حاول مرة أخرى');}finally{setBusy(false);}}
  async function addDriver(){if(!selectedFleet||!selectedDriver)return;setBusy(true);try{await setFleetDriver({fleetId:selectedFleet,driverId:selectedDriver,active:true,commissionPercent:driverCut.trim()?num(driverCut):null});setSelectedDriver(null);setDriverSearch('');setDriverCut('');await refresh();}catch(e){Alert.alert('تعذر إضافة المندوب',e instanceof Error?e.message:'حاول مرة أخرى');}finally{setBusy(false);}}
  async function topup(walletId:string){const amount=num(walletAmounts[walletId]);if(amount<=0)return;setBusy(true);try{await postWalletAdjustment(walletId,amount,'شحن محفظة من الإدارة');setWalletAmounts(x=>({...x,[walletId]:''}));await refresh();}catch(e){Alert.alert('تعذر شحن المحفظة',e instanceof Error?e.message:'حاول مرة أخرى');}finally{setBusy(false);}}
  async function createReward(){if(rewardTitle.trim().length<3||num(rewardCost)<=0)return;setBusy(true);try{await upsertReward({title:rewardTitle,targetRole:rewardRole,rewardType,pointsCost:Math.round(num(rewardCost)),active:true});setRewardTitle('');await refresh();}catch(e){Alert.alert('تعذر إضافة المكافأة',e instanceof Error?e.message:'حاول مرة أخرى');}finally{setBusy(false);}}
  async function toggleReward(r:any){try{await upsertReward({id:r.id,title:r.title,description:r.description??'',targetRole:r.target_role,rewardType:r.reward_type,pointsCost:Number(r.points_cost),rewardValue:r.reward_value==null?null:Number(r.reward_value),active:!r.active});await refresh();}catch(e){Alert.alert('تعذر تعديل المكافأة',e instanceof Error?e.message:'حاول مرة أخرى');}}

  if(query.isLoading)return <View style={s.center}><Muted>جاري تجهيز المركز المالي…</Muted></View>;
  if(query.isError)return <View style={s.center}><Title>تعذر تحميل المركز المالي</Title><Muted>{query.error instanceof Error?query.error.message:'حاول مرة أخرى'}</Muted></View>;
  return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <View style={s.hero}><Text style={s.kicker}>FINANCE • FLEETS • REWARDS</Text><Text style={s.heroTitle}>مركز التحكم المالي</Text><Text style={s.heroText}>العمولات، محافظ التجار والمناديب، شركات التشغيل، جودة المندوبين والمكافآت — كلها من مكان واحد وبسجل مالي غير قابل للتعديل من العميل.</Text><View style={s.metrics}><Metric label="محافظ" value={String(data?.wallets.length??0)}/><Metric label="مديونيات" value={`${totalDebt.toFixed(0)} ج`}/><Metric label="شركات" value={String(data?.fleets.length??0)}/><Metric label="مكافآت" value={String(data?.rewards.length??0)}/></View></View>

    <Text style={s.section}>العمولات وحدود المديونية</Text>
    <Card><Field label="عمولة المنصة من المندوب المباشر %" value={direct??String(settings?.driver_platform_commission_percent??0)} onChangeText={setDirect} keyboardType="decimal-pad"/><Field label="عمولة المنصة من مندوب تابع لشركة %" value={fleetDriver??String(settings?.fleet_driver_platform_commission_percent??0)} onChangeText={setFleetDriverPct} keyboardType="decimal-pad"/><Field label="عمولة المنصة من الشركة %" value={fleetPlatform??String(settings?.fleet_platform_commission_percent??0)} onChangeText={setFleetPlatform} keyboardType="decimal-pad"/><Field label="عمولة المنصة من التاجر %" value={merchant??String(settings?.merchant_platform_commission_percent??0)} onChangeText={setMerchant} keyboardType="decimal-pad"/><View style={s.divider}/><Field label="حد مديونية المندوب" value={driverDebt??String(settings?.driver_debt_limit??500)} onChangeText={setDriverDebt} keyboardType="decimal-pad"/><Field label="حد مديونية التاجر" value={merchantDebt??String(settings?.merchant_debt_limit??1000)} onChangeText={setMerchantDebt} keyboardType="decimal-pad"/><Field label="حد مديونية الشركة" value={fleetDebt??String(settings?.fleet_debt_limit??3000)} onChangeText={setFleetDebt} keyboardType="decimal-pad"/><Toggle title="تفعيل إيقاف العمل عند حد المديونية" value={enforcement??Boolean(settings?.wallet_enforcement_enabled)} onPress={()=>setEnforcement(v=>!(v??Boolean(settings?.wallet_enforcement_enabled)))}/><Toggle title="تفعيل مكافأة الجودة حسب التقييم" value={ratingBonus??Boolean(settings?.rating_bonus_enabled)} onPress={()=>setRatingBonus(v=>!(v??Boolean(settings?.rating_bonus_enabled)))}/><Muted>النظام الحالي عند التفعيل: 4.8+ = زيادة 10%، 4.6+ = زيادة 5%، أقل من كده الأجر الأساسي كما هو. مفيش خصم عقابي تلقائي بسبب تقييم واحد.</Muted><Button title={busy?'جاري الحفظ…':'حفظ النظام المالي'} disabled={busy} onPress={()=>void saveFinance()}/></Card>

    <Text style={s.section}>شركات التشغيل ومديريها</Text>
    <Card><Text style={s.cardTitle}>إنشاء شركة جديدة</Text><Muted>صاحب الشركة لا يأخذ صلاحية أدمن المنصة؛ يشوف شركته ومناديبه ومحفظته فقط.</Muted><Field value={companyName} onChangeText={setCompanyName} placeholder="اسم الشركة"/><Field value={ownerSearch} onChangeText={setOwnerSearch} placeholder="ابحث عن صاحب الشركة بالاسم أو الهاتف"/>{ownerSearch.trim()?owners.map((p:any)=><Pick key={p.id} active={selectedOwner===p.id} title={p.full_name||p.phone||'حساب'} subtitle={p.phone||''} onPress={()=>setSelectedOwner(p.id)}/>):null}<Field value={companyCut} onChangeText={setCompanyCut} keyboardType="decimal-pad" placeholder="نسبة الشركة من المندوب %"/><Button title="إنشاء وربط مدير الشركة" disabled={busy||!selectedOwner||companyName.trim().length<2} onPress={()=>void addCompany()}/></Card>
    {(data?.fleets??[]).map((f:any)=><Card key={f.id}><View style={s.row}><View style={s.flex}><Text style={s.cardTitle}>{f.name}</Text><Muted>عمولة المناديب {Number(f.driver_commission_percent).toFixed(1)}% • {f.status}</Muted></View><Pressable onPress={()=>setSelectedFleet(f.id)} style={[s.smallButton,selectedFleet===f.id&&s.smallButtonActive]}><Text style={s.smallButtonText}>{selectedFleet===f.id?'مختارة':'اختيار'}</Text></Pressable></View></Card>)}
    {selectedFleet?<Card><Text style={s.cardTitle}>إضافة مندوب للشركة المختارة</Text><Field value={driverSearch} onChangeText={setDriverSearch} placeholder="ابحث عن مندوب معتمد"/>{driverSearch.trim()?driverCandidates.map((p:any)=><Pick key={p.id} active={selectedDriver===p.id} title={p.full_name||p.phone||'مندوب'} subtitle={p.phone||''} onPress={()=>setSelectedDriver(p.id)}/>):null}<Field value={driverCut} onChangeText={setDriverCut} keyboardType="decimal-pad" placeholder="نسبة خاصة للمندوب — اختياري"/><Button title="ربط المندوب بالشركة" disabled={busy||!selectedDriver} onPress={()=>void addDriver()}/></Card>:null}

    <Text style={s.section}>المحافظ والمديونيات</Text>
    {!debts.length?<Card><Muted>مفيش مديونيات حالية.</Muted></Card>:debts.slice(0,30).map((w:any)=><Card key={w.id}><View style={s.row}><View style={s.flex}><Text style={s.cardTitle}>{w.owner_kind==='driver'?'مندوب':w.owner_kind==='merchant'?'تاجر':'شركة'}</Text><Muted>حد المديونية {Number(w.debt_limit).toFixed(0)} ج</Muted></View><Text style={s.debt}>{Number(w.balance).toFixed(2)} ج</Text></View><Field value={walletAmounts[w.id]??''} onChangeText={v=>setWalletAmounts(x=>({...x,[w.id]:v}))} keyboardType="decimal-pad" placeholder="مبلغ الشحن"/><Button title="إضافة شحن للمحفظة" disabled={busy||num(walletAmounts[w.id])<=0} onPress={()=>void topup(w.id)}/></Card>)}

    <Text style={s.section}>نظام النقاط</Text>
    <Card><Field label="نقاط العميل لكل 10 جنيه" value={customerPts??String(loyalty?.customer_points_per_10??1)} onChangeText={setCustomerPts} keyboardType="decimal-pad"/><Field label="نقاط المندوب لكل توصيل" value={driverPts??String(loyalty?.driver_points_per_delivery??5)} onChangeText={setDriverPts} keyboardType="number-pad"/><Field label="نقاط التاجر لكل طلب مكتمل" value={merchantPts??String(loyalty?.merchant_points_per_delivered_order??3)} onChangeText={setMerchantPts} keyboardType="number-pad"/><Field label="نقاط دعوة الصديق" value={referralPts??String(loyalty?.referral_points??50)} onChangeText={setReferralPts} keyboardType="number-pad"/><Button title="حفظ قواعد النقاط" disabled={busy} onPress={()=>void saveLoyalty()}/></Card>

    <Text style={s.section}>كتالوج الجوائز</Text>
    <Card><Text style={s.cardTitle}>إضافة جائزة</Text><Field value={rewardTitle} onChangeText={setRewardTitle} placeholder="مثلاً: توصيل مجاني للطلب القادم"/><Field value={rewardCost} onChangeText={setRewardCost} keyboardType="number-pad" placeholder="عدد النقاط المطلوبة"/><Text style={s.label}>الفئة المستهدفة</Text><View style={s.chips}>{(['customer','driver','merchant','all'] as const).map(r=><Chip key={r} active={rewardRole===r} title={roleLabel[r]} onPress={()=>setRewardRole(r)}/>)}</View><Text style={s.label}>نوع الجائزة</Text><View style={s.chips}>{(['free_delivery','commission_free_next_order','priority_badge','custom'] as const).map(t=><Chip key={t} active={rewardType===t} title={rewardTypeLabel[t]} onPress={()=>setRewardType(t)}/>)}</View><Button title="إضافة الجائزة" disabled={busy||rewardTitle.trim().length<3||num(rewardCost)<=0} onPress={()=>void createReward()}/></Card>
    {(data?.rewards??[]).map((r:any)=><Card key={r.id}><View style={s.row}><View style={s.flex}><Text style={s.cardTitle}>{r.title}</Text><Muted>{roleLabel[r.target_role]} • {rewardTypeLabel[r.reward_type]??r.reward_type} • {r.points_cost} نقطة</Muted></View><Pressable onPress={()=>void toggleReward(r)} style={[s.status,r.active?s.statusOn:s.statusOff]}><Text style={[s.statusText,!r.active&&s.statusTextOff]}>{r.active?'مفعّلة':'موقوفة'}</Text></Pressable></View></Card>)}

    <Text style={s.section}>آخر حسابات المندوبين</Text>
    {(data?.earnings??[]).slice(0,20).map((e:any)=><Card key={e.order_id}><View style={s.row}><View style={s.flex}><Text style={s.cardTitle}>طلب #{String(e.order_id).slice(0,8)}</Text><Muted>التقييم وقت الحساب: {Number(e.rating_snapshot??0).toFixed(2)} • مكافأة جودة {Number(e.quality_bonus_amount??0).toFixed(2)} ج</Muted></View><Text style={s.net}>{Number(e.driver_net_amount).toFixed(2)} ج</Text></View><Muted>رسوم التوصيل {Number(e.gross_delivery_fee).toFixed(2)} • عمولة منصة {Number(e.platform_commission_amount).toFixed(2)} • عمولة شركة {Number(e.fleet_commission_amount).toFixed(2)}</Muted></Card>)}
  </ScrollView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Toggle({title,value,onPress}:{title:string;value:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={s.toggle}><Text style={s.toggleTitle}>{title}</Text><View style={[s.switch,value&&s.switchOn]}><View style={[s.knob,value&&s.knobOn]}/></View></Pressable>}
function Pick({active,title,subtitle,onPress}:{active:boolean;title:string;subtitle:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.pick,active&&s.pickActive]}><View style={s.flex}><Text style={s.pickTitle}>{title}</Text><Text style={s.pickSub}>{subtitle}</Text></View><Text style={s.check}>{active?'✓':'اختيار'}</Text></Pressable>}
function Chip({active,title,onPress}:{active:boolean;title:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&s.chipTextActive]}>{title}</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fb'},content:{padding:18,paddingBottom:50,gap:13,direction:'rtl'},center:{flex:1,justifyContent:'center',padding:28,backgroundColor:'#f5f7fb',gap:8},hero:{backgroundColor:'#101828',borderRadius:30,padding:23,gap:9},kicker:{color:'#fdb022',fontWeight:'900',textAlign:'right',fontSize:11},heroTitle:{color:'#fff',fontSize:30,fontWeight:'900',textAlign:'right'},heroText:{color:'#d0d5dd',lineHeight:22,textAlign:'right'},metrics:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8},metric:{width:'48%',backgroundColor:'rgba(255,255,255,.08)',borderRadius:15,padding:11},metricValue:{color:'#fff',fontSize:20,fontWeight:'900',textAlign:'right'},metricLabel:{color:'#cbd5e1',fontSize:10,textAlign:'right'},section:{fontSize:21,fontWeight:'900',color:'#101828',textAlign:'right',marginTop:3},cardTitle:{fontSize:16,fontWeight:'900',color:'#344054',textAlign:'right'},divider:{height:1,backgroundColor:'#eaecf0',marginVertical:3},toggle:{minHeight:48,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',gap:10},toggleTitle:{fontWeight:'800',color:'#344054',textAlign:'right',flex:1},switch:{width:48,height:28,borderRadius:14,backgroundColor:'#d0d5dd',padding:3},switchOn:{backgroundColor:colors.primary},knob:{width:22,height:22,borderRadius:11,backgroundColor:'#fff'},knobOn:{alignSelf:'flex-end'},row:{flexDirection:'row-reverse',alignItems:'center',gap:10},flex:{flex:1},smallButton:{borderRadius:12,borderWidth:1,borderColor:'#d0d5dd',paddingHorizontal:11,paddingVertical:7},smallButtonActive:{backgroundColor:'#fff4ed',borderColor:colors.primary},smallButtonText:{fontWeight:'900',color:'#b93815'},pick:{flexDirection:'row-reverse',alignItems:'center',borderWidth:1,borderColor:'#eaecf0',borderRadius:14,padding:10,gap:8},pickActive:{borderColor:colors.primary,backgroundColor:'#fff4ed'},pickTitle:{fontWeight:'900',color:'#344054',textAlign:'right'},pickSub:{fontSize:10,color:'#667085',textAlign:'right'},check:{fontWeight:'900',color:colors.primary},debt:{fontSize:19,fontWeight:'900',color:'#b42318'},label:{fontWeight:'900',color:'#475467',textAlign:'right'},chips:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#d0d5dd',borderRadius:999,paddingHorizontal:10,paddingVertical:7},chipActive:{backgroundColor:'#fff4ed',borderColor:colors.primary},chipText:{fontSize:11,fontWeight:'800',color:'#475467'},chipTextActive:{color:'#b93815'},status:{borderRadius:999,paddingHorizontal:9,paddingVertical:5},statusOn:{backgroundColor:'#ecfdf3'},statusOff:{backgroundColor:'#f2f4f7'},statusText:{fontWeight:'900',fontSize:10,color:'#067647'},statusTextOff:{color:'#667085'},net:{fontSize:18,fontWeight:'900',color:'#067647'}});