import { useQuery } from '@tanstack/react-query';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Image } from 'expo-image';
import { Button, Card, Muted, Title, colors } from '@/src/components/ui';
import { getMyRoles } from '@/src/lib/api';
import { supabase } from '@/src/lib/supabase';
import { getOnboardingIdentity } from '@/src/lib/onboarding';

const names={customer:'عميل',merchant:'تاجر',driver:'مندوب',admin:'إدارة'} as const;
export default function Account(){
  const roles=useQuery({queryKey:['roles'],queryFn:getMyRoles});
  const profile=useQuery({queryKey:['profile-summary'],queryFn:getOnboardingIdentity});
  const list=roles.data??[];
  return <ScrollView style={s.page} contentContainerStyle={s.content}>
    <View style={s.hero}><View style={s.profileRow}>{profile.data?.avatar_url?<Image source={{uri:profile.data.avatar_url}} style={s.avatar} contentFit="cover"/>:<View style={s.avatarPlaceholder}><Text style={s.avatarLetter}>{(profile.data?.full_name||'م')[0]}</Text></View>}<View style={s.flex}><Text style={s.name}>{profile.data?.full_name||'حساب طلباتك'}</Text><Text style={s.phone}>{profile.data?.phone||''}</Text><View style={s.roles}>{list.map(role=><View key={role} style={s.roleBadge}><Text style={s.roleText}>{names[role]}</Text></View>)}</View></View></View></View>
    <Text style={s.section}>الخدمات الأساسية</Text><View style={s.grid}><Tile icon="📍" title="عناويني" onPress={()=>router.push('/addresses')}/><Tile icon="❤️" title="المفضلة" onPress={()=>router.push('/favorites')}/><Tile icon="🔔" title="الإشعارات" onPress={()=>router.push('/notifications')}/><Tile icon="🤲" title="الأذكار" onPress={()=>router.push('/adhkar')}/></View>
    <Text style={s.section}>الحساب والأمان</Text><Card><Menu title="بياناتي والخصوصية" icon="👤" onPress={()=>router.push('/privacy')}/><Divider/><Menu title="الأمان والرقم السري" icon="🔐" onPress={()=>router.push('/security')}/><Divider/><Menu title="الدعم والشكاوى" icon="💬" onPress={()=>router.push('/support')}/></Card>
    <Text style={s.section}>استخدم طلباتك في شغلك</Text><Card><Text style={s.cardTitle}>تاجر أو مندوب؟</Text><Muted>سجل نشاطك أو بيانات التوصيل والمستندات، والإدارة تراجع الطلب قبل تفعيل الدور.</Muted><Button title="الانضمام كتاجر أو مندوب" onPress={()=>router.push('/applications')}/></Card>
    {list.includes('merchant')||list.includes('driver')||list.includes('admin')?<><Text style={s.section}>لوحات العمل</Text><Card>{list.includes('merchant')?<Menu title="لوحة التاجر" icon="🏪" onPress={()=>router.push('/role/merchant')}/>:null}{list.includes('driver')?<><Divider/><Menu title="لوحة المندوب" icon="🛵" onPress={()=>router.push('/role/driver')}/></>:null}{list.includes('admin')?<><Divider/><Menu title="مركز الإدارة" icon="⚙️" onPress={()=>router.push('/admin')}/></>:null}</Card></>:null}
    <Pressable accessibilityRole="button" style={s.logout} onPress={async()=>{const{error}=await supabase.auth.signOut();if(error)return Alert.alert('تعذر الخروج',error.message);router.replace('/login');}}><Text style={s.logoutText}>تسجيل الخروج</Text></Pressable>
  </ScrollView>;
}
function Tile({icon,title,onPress}:{icon:string;title:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={s.tile}><Text style={s.tileIcon}>{icon}</Text><Text style={s.tileTitle}>{title}</Text></Pressable>}
function Menu({icon,title,onPress}:{icon:string;title:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={s.menu}><Text style={s.menuIcon}>{icon}</Text><Text style={s.menuTitle}>{title}</Text><Text style={s.chevron}>‹</Text></Pressable>}
function Divider(){return <View style={s.divider}/>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fa'},content:{padding:18,paddingBottom:44,gap:13,direction:'rtl'},hero:{backgroundColor:'#17212f',borderRadius:30,padding:22},profileRow:{flexDirection:'row-reverse',alignItems:'center',gap:14},avatar:{width:76,height:76,borderRadius:24,backgroundColor:'#344054'},avatarPlaceholder:{width:76,height:76,borderRadius:24,backgroundColor:'#344054',alignItems:'center',justifyContent:'center'},avatarLetter:{fontSize:30,fontWeight:'900',color:'#fff'},flex:{flex:1},name:{fontSize:22,fontWeight:'900',color:'#fff',textAlign:'right'},phone:{color:'#d0d5dd',fontSize:13,textAlign:'right',marginTop:3},roles:{flexDirection:'row-reverse',flexWrap:'wrap',gap:5,marginTop:8},roleBadge:{backgroundColor:'#253246',borderRadius:999,paddingHorizontal:9,paddingVertical:4},roleText:{color:'#fdba74',fontSize:10,fontWeight:'900'},section:{fontSize:19,fontWeight:'900',color:'#101828',textAlign:'right',marginTop:4},grid:{flexDirection:'row-reverse',flexWrap:'wrap',gap:9},tile:{width:'48%',minHeight:105,backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:'#eaecf0',alignItems:'center',justifyContent:'center',gap:7},tileIcon:{fontSize:27},tileTitle:{fontWeight:'900',color:'#344054'},menu:{minHeight:52,flexDirection:'row-reverse',alignItems:'center',gap:11},menuIcon:{fontSize:20},menuTitle:{flex:1,fontWeight:'800',color:'#344054',textAlign:'right'},chevron:{fontSize:28,color:'#98a2b3'},divider:{height:1,backgroundColor:'#f2f4f7'},cardTitle:{fontSize:17,fontWeight:'900',color:colors.text,textAlign:'right'},logout:{minHeight:50,borderRadius:15,borderWidth:1,borderColor:'#fda29b',backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},logoutText:{color:'#b42318',fontWeight:'900'}});
