import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Muted, colors } from '@/src/components/ui';
import { getMyOrders } from '@/src/lib/api';

const labels:Record<string,string>={pending:'بانتظار التاجر',accepted:'تم القبول',preparing:'جاري التحضير',ready:'جاهز للاستلام',assigned:'تم تعيين مندوب',picked_up:'استلم المندوب الطلب',on_the_way:'المندوب في الطريق',delivered:'تم التسليم',cancelled:'ملغي',rejected:'مرفوض'};
const activeStatuses=new Set(['pending','accepted','preparing','ready','assigned','picked_up','on_the_way']);

export default function Orders(){
  const query=useQuery({queryKey:['my-orders'],queryFn:getMyOrders,refetchInterval:15_000});
  const [filter,setFilter]=useState<'all'|'active'|'done'>('all');
  const visible=useMemo(()=>{const rows=query.data??[];if(filter==='active')return rows.filter(x=>activeStatuses.has(x.status));if(filter==='done')return rows.filter(x=>!activeStatuses.has(x.status));return rows;},[query.data,filter]);
  const active=(query.data??[]).filter(x=>activeStatuses.has(x.status)).length;
  return <View style={s.page}><FlatList data={visible} keyExtractor={x=>x.id} refreshing={query.isFetching} onRefresh={()=>query.refetch()} contentContainerStyle={s.content} ListHeaderComponent={<View style={s.header}>
    <View style={s.hero}><Text style={s.kicker}>طلباتك</Text><Text style={s.heroTitle}>تابع كل طلب من أول تأكيد لحد باب البيت</Text><View style={s.heroStat}><Text style={s.heroStatValue}>{active}</Text><Text style={s.heroStatText}>طلب نشط دلوقتي</Text></View></View>
    <View style={s.filters}><Chip title="الكل" active={filter==='all'} onPress={()=>setFilter('all')}/><Chip title="الجارية" active={filter==='active'} onPress={()=>setFilter('active')}/><Chip title="السابقة" active={filter==='done'} onPress={()=>setFilter('done')}/></View>
  </View>} ListEmptyComponent={<View style={s.empty}><Text style={s.emptyIcon}>📦</Text><Text style={s.emptyTitle}>{query.isLoading?'جاري تحميل طلباتك…':'مفيش طلبات هنا'}</Text><Muted>{query.isLoading?'':'لما تعمل طلب جديد هتلاقيه هنا وتتابعه لحظة بلحظة.'}</Muted>{!query.isLoading?<Pressable onPress={()=>router.replace('/home')} style={s.shop}><Text style={s.shopText}>ابدأ طلب جديد</Text></Pressable>:null}</View>} renderItem={({item})=>{const isActive=activeStatuses.has(item.status);return <Pressable accessibilityRole="button" accessibilityLabel={`تتبع الطلب ${item.id.slice(0,8)}`} onPress={()=>router.push(`/order/${item.id}`)} style={({pressed})=>[s.order,pressed&&{opacity:.92}]}><View style={s.orderTop}><View style={s.flex}><Text style={s.orderNo}>طلب #{item.id.slice(0,8)}</Text><Text style={s.date}>{new Date(item.created_at).toLocaleString('ar-EG')}</Text></View><Text style={s.price}>{item.total.toFixed(2)} ج</Text></View><View style={s.orderBottom}><View style={[s.status,isActive?s.statusActive:item.status==='delivered'?s.statusDone:s.statusMuted]}><Text style={[s.statusText,isActive?s.statusTextActive:item.status==='delivered'?s.statusTextDone:s.statusTextMuted]}>{labels[item.status]??item.status}</Text></View><Text style={s.follow}>{isActive?'تتبع مباشر ←':'التفاصيل ←'}</Text></View></Pressable>}}/></View>;
}
function Chip({title,active,onPress}:{title:string;active:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&s.chipTextActive]}>{title}</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fa'},content:{padding:18,paddingBottom:44,gap:11},header:{gap:13},hero:{backgroundColor:'#17212f',borderRadius:30,padding:22,gap:7},kicker:{color:'#fb923c',fontWeight:'900',fontSize:12,textAlign:'right'},heroTitle:{color:'#fff',fontSize:25,fontWeight:'900',lineHeight:33,textAlign:'right'},heroStat:{flexDirection:'row-reverse',alignItems:'baseline',gap:7,marginTop:6},heroStatValue:{color:'#fdba74',fontSize:27,fontWeight:'900'},heroStatText:{color:'#d0d5dd',fontSize:12},filters:{flexDirection:'row-reverse',gap:8},chip:{flex:1,paddingVertical:10,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#eaecf0',alignItems:'center'},chipActive:{backgroundColor:'#fff4ed',borderColor:colors.primary},chipText:{fontWeight:'800',fontSize:12,color:'#667085'},chipTextActive:{color:'#b93815'},order:{backgroundColor:'#fff',borderRadius:22,borderWidth:1,borderColor:'#eaecf0',padding:16,gap:13},orderTop:{flexDirection:'row-reverse',alignItems:'flex-start',gap:10},flex:{flex:1},orderNo:{fontSize:17,fontWeight:'900',color:'#101828',textAlign:'right'},date:{fontSize:11,color:'#98a2b3',textAlign:'right',marginTop:4},price:{fontSize:18,fontWeight:'900',color:'#101828'},orderBottom:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',gap:8},status:{borderRadius:999,paddingHorizontal:10,paddingVertical:6},statusActive:{backgroundColor:'#fffaeb'},statusDone:{backgroundColor:'#ecfdf3'},statusMuted:{backgroundColor:'#f2f4f7'},statusText:{fontSize:11,fontWeight:'900'},statusTextActive:{color:'#b54708'},statusTextDone:{color:'#067647'},statusTextMuted:{color:'#667085'},follow:{fontSize:11,fontWeight:'900',color:colors.primary},empty:{alignItems:'center',paddingVertical:55,gap:7},emptyIcon:{fontSize:44},emptyTitle:{fontSize:19,fontWeight:'900',color:'#344054'},shop:{marginTop:8,backgroundColor:colors.primary,borderRadius:14,paddingHorizontal:18,paddingVertical:11},shopText:{color:'#fff',fontWeight:'900'}});
