import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, router } from 'expo-router';
import { Button, Card, Field, Muted, PasswordField, Title, colors } from '@/src/components/ui';
import { signUpPhonePassword, type RegistrationKind } from '@/src/lib/auth';

type Kind=RegistrationKind;
const kinds:{key:Kind;title:string;subtitle:string;icon:string}[]=[
  {key:'customer',title:'عميل',subtitle:'اطلب من المتاجر وتابع طلباتك',icon:'🛍️'},
  {key:'merchant',title:'تاجر',subtitle:'بيانات الحساب ثم مستندات النشاط قبل إرسال التسجيل',icon:'🏪'},
  {key:'driver',title:'مندوب',subtitle:'بيانات الحساب ثم الهوية ومستندات وسيلة التوصيل',icon:'🛵'},
];

const merchantDocs=['بطاقة الرقم القومي — وش وظهر','السجل التجاري','لوجو / صورة النشاط','موقع النشاط'];
const driverDocs=['صورة شخصية واضحة','بطاقة الرقم القومي — وش وظهر','للموتوسيكل: رخصة قيادة وش وظهر','للموتوسيكل: رخصة المركبة وش وظهر'];

export default function Signup(){
  const[kind,setKind]=useState<Kind>('customer');const[name,setName]=useState('');const[phone,setPhone]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[referralCode,setReferralCode]=useState('');const[busy,setBusy]=useState(false);
  const passwordsMatch=password.length>=8&&password===confirm;
  const businessRegistration=kind==='merchant'||kind==='driver';
  const requiredDocs=kind==='merchant'?merchantDocs:kind==='driver'?driverDocs:[];
  async function submit(){if(!passwordsMatch){Alert.alert('راجع كلمة المرور','كلمتا المرور غير متطابقتين.');return;}setBusy(true);try{await signUpPhonePassword({name,phone,password,kind,referralCode});if(kind==='customer')router.replace('/home');else router.replace({pathname:'/onboarding',params:{role:kind,registration:'first'}});}catch(e){Alert.alert('تعذر إنشاء الحساب',e instanceof Error?e.message:'راجع البيانات وحاول مرة أخرى');}finally{setBusy(false);}}
  return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <View style={s.hero}><Text style={s.brand}>طلباتك</Text><Text style={s.heroTitle}>{businessRegistration?'تسجيلك كامل من أول مرة':'حساب واحد يبدأ صح من أول خطوة'}</Text><Text style={s.heroText}>{businessRegistration?'تسجيل التاجر أو المندوب مرحلتين متصلتين: بيانات الحساب، ثم البيانات والمستندات المطلوبة. التسجيل مش بيكتمل ولا بيتبعت للمراجعة قبل إنهاء المرحلتين.':'اختار استخدامك وأنشئ حسابك برقم الموبايل وكلمة المرور.'}</Text></View>
    <View style={s.kindGrid}>{kinds.map(item=><Pressable key={item.key} accessibilityRole="button" onPress={()=>setKind(item.key)} style={[s.kind,kind===item.key&&s.kindActive]}><Text style={s.kindIcon}>{item.icon}</Text><Text style={[s.kindTitle,kind===item.key&&s.kindTitleActive]}>{item.title}</Text><Text style={[s.kindSub,kind===item.key&&s.kindSubActive]}>{item.subtitle}</Text></Pressable>)}</View>

    {businessRegistration?<View style={s.progress}><View style={[s.progressStep,s.progressActive]}><Text style={s.progressNo}>1</Text><Text style={s.progressTitle}>بيانات الحساب</Text></View><View style={s.progressLine}/><View style={s.progressStep}><Text style={s.progressNoMuted}>2</Text><Text style={s.progressTitleMuted}>المستندات المطلوبة</Text></View></View>:null}

    <Card><Title>بيانات الحساب</Title><Muted>{kind==='customer'?'حساب العميل يتفعل مباشرة بعد التسجيل.':'دي المرحلة الأولى فقط. بعد الضغط على «التالي» هتكمل المستندات المطلوبة قبل إرسال طلبك للإدارة.'}</Muted><Field accessibilityLabel="الاسم الكامل" placeholder="الاسم الكامل" value={name} onChangeText={setName}/><Field accessibilityLabel="رقم الهاتف" keyboardType="phone-pad" placeholder="رقم الموبايل — مثال 01012345678" value={phone} onChangeText={setPhone}/><PasswordField accessibilityLabel="كلمة المرور" placeholder="كلمة المرور — 8 أحرف على الأقل" value={password} onChangeText={setPassword}/><PasswordField accessibilityLabel="تأكيد كلمة المرور" placeholder="تأكيد كلمة المرور" value={confirm} onChangeText={setConfirm}/>{confirm.length>0?<Text style={[s.match,{color:passwordsMatch?'#067647':'#b42318'}]}>{passwordsMatch?'✓ كلمة المرور متطابقة':'كلمتا المرور غير متطابقتين'}</Text>:null}</Card>

    {businessRegistration?<Card><Text style={s.docsTitle}>المستندات اللي هتحتاجها في الخطوة التالية</Text><Muted>جهّز صور واضحة للمستندات. الحقول المطلوبة لازم تترفع قبل ما زر إرسال التسجيل للإدارة يتفعل.</Muted>{requiredDocs.map(item=><View key={item} style={s.docRow}><Text style={s.docCheck}>✓</Text><Text style={s.docText}>{item}</Text></View>)}<View style={s.notice}><Text style={s.noticeText}>{kind==='merchant'?'البطاقة الضريبية اختيارية حاليًا.':'لو هتشتغل بدراجة، مش هنطلب رخصة قيادة أو رخصة مركبة.'}</Text></View></Card>:null}

    <Card><Text style={s.refTitle}>كود دعوة — اختياري</Text><Muted>لو حد دعاك لطلباتك، اكتب الكود هنا وقت إنشاء الحساب لأول مرة. بعد أول نشاط مكتمل ليك، كل واحد فيكم بياخد 50 نقطة.</Muted><Field accessibilityLabel="كود الدعوة" placeholder="مثال: A1B2C3D4" autoCapitalize="characters" value={referralCode} onChangeText={setReferralCode}/></Card>

    <Button title={busy?'جاري تجهيز التسجيل…':kind==='merchant'?'التالي: بيانات النشاط والمستندات':kind==='driver'?'التالي: بيانات المندوب والمستندات':'إنشاء حساب العميل'} onPress={submit} disabled={busy||name.trim().length<2||!phone.trim()||!passwordsMatch}/>
    {businessRegistration?<Text style={s.requiredNote}>لن يتم إرسال تسجيل {kind==='merchant'?'التاجر':'المندوب'} للمراجعة قبل رفع كل المستندات المطلوبة في الخطوة التالية.</Text>:null}
    <Link href="/login" style={s.login}>عندي حساب بالفعل — تسجيل الدخول</Link>
  </ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f6f7f9'},content:{padding:18,paddingBottom:38,gap:15,direction:'rtl'},hero:{backgroundColor:'#17212f',borderRadius:30,padding:24,gap:8},brand:{color:'#fb923c',fontWeight:'900',fontSize:18,textAlign:'right'},heroTitle:{color:'#fff',fontSize:27,fontWeight:'900',lineHeight:36,textAlign:'right'},heroText:{color:'#d0d5dd',fontSize:14,lineHeight:23,textAlign:'right'},kindGrid:{gap:9},kind:{backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:'#e4e7ec',padding:14,flexDirection:'row-reverse',alignItems:'center',gap:10},kindActive:{backgroundColor:'#fff4ed',borderColor:colors.primary,borderWidth:2},kindIcon:{fontSize:26},kindTitle:{fontWeight:'900',fontSize:17,color:'#1d2939'},kindTitleActive:{color:'#b93815'},kindSub:{flex:1,color:'#667085',fontSize:12,textAlign:'right'},kindSubActive:{color:'#7a271a'},progress:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',paddingHorizontal:8},progressStep:{alignItems:'center',gap:5,minWidth:100},progressActive:{},progressNo:{width:30,height:30,borderRadius:15,backgroundColor:colors.primary,color:'#fff',textAlign:'center',textAlignVertical:'center',fontWeight:'900',paddingTop:5},progressNoMuted:{width:30,height:30,borderRadius:15,backgroundColor:'#e4e7ec',color:'#667085',textAlign:'center',fontWeight:'900',paddingTop:5},progressTitle:{fontSize:11,fontWeight:'900',color:'#b93815'},progressTitleMuted:{fontSize:11,fontWeight:'800',color:'#667085'},progressLine:{height:2,flex:1,maxWidth:90,backgroundColor:'#e4e7ec',marginBottom:20},match:{fontSize:12,fontWeight:'800',textAlign:'right'},docsTitle:{fontWeight:'900',fontSize:17,color:'#101828',textAlign:'right'},docRow:{flexDirection:'row-reverse',alignItems:'center',gap:8,paddingVertical:3},docCheck:{color:'#067647',fontWeight:'900',fontSize:14},docText:{flex:1,textAlign:'right',color:'#344054',fontSize:13,fontWeight:'700'},notice:{backgroundColor:'#fff4ed',borderRadius:12,padding:10,marginTop:4},noticeText:{color:'#9a3412',fontSize:12,lineHeight:19,textAlign:'right',fontWeight:'700'},refTitle:{fontWeight:'900',fontSize:17,color:'#101828',textAlign:'right'},requiredNote:{textAlign:'center',color:'#b54708',fontSize:12,lineHeight:19,fontWeight:'800',paddingHorizontal:8},login:{textAlign:'center',color:colors.primary,fontWeight:'800',paddingVertical:10}});